projectOverride: null

default:
  app:
    enableAutoSync: true
    autoSyncPrune: true
    autoSelfHeal: true

    destination:
      server: "https://kubernetes.default.svc"

    project: "default"

    source:
      repoURL: git@github.com:Redjon27/deployment-aplications.git
      targetRevision: main

applications:
  devops-tech-challenge:
    enabled:
      dev: true
      test: true
      prod: true
    source:
      path: "devops-tech-challenge"