{{- range $appName, $appCfg := .Values.applications }}
  {{- $enabledMap := $appCfg.enabled | default dict -}}
  {{- range $env, $flag := $enabledMap }}
    {{- if $flag }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $env }}-{{ $appName }}
  namespace: argocd
spec:
  destination:
    namespace: {{ $env | quote }}
    server: {{ $.Values.default.app.destination.server | quote }}

  project: {{ $.Values.projectOverride | default $.Values.default.app.project | quote }}

  {{- if $appCfg.enableAutoSync | default $.Values.default.app.enableAutoSync }}
  syncPolicy:
    automated:
      prune: {{ $appCfg.autoSyncPrune | default $.Values.default.app.autoSyncPrune | default true }}
      selfHeal: {{ $appCfg.autoSelfHeal | default $.Values.default.app.autoSelfHeal | default true }}
  {{- end }}

  source:
    repoURL: {{ $appCfg.source.repoURL | default $.Values.default.app.source.repoURL | quote }}
    targetRevision: {{ $appCfg.source.targetRevision | default $.Values.default.app.source.targetRevision | quote }}
    path: {{ required (printf "applications.%s.source.path is required" $appName) $appCfg.source.path | quote }}
    helm:
      valueFiles:
        - {{ printf "values.%s.yaml" $env | quote }}
    {{- end }}
  {{- end }}
{{- end }}
