{{- $envs := .Values.environments | default (list "dev") -}}

{{- range $env := $envs }}
  {{- $_ := set $ "curEnv" $env }}

  {{- range $key, $val := $.Values.applications }}
    {{- if $val.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $env }}-{{ $key }}
  namespace: argocd
spec:
  destination:
    namespace: {{ $env }}
    server: {{ $.Values.default.app.destination.server | quote }}

  project: {{ $.Values.projectOverride | default $.Values.default.app.project | quote }}

  {{- if $val.enableAutoSync | default $.Values.default.app.enableAutoSync }}
  syncPolicy:
    automated:
      prune: {{ $val.autoSyncPrune | default $.Values.default.app.autoSyncPrune | default true }}
      selfHeal: {{ $val.autoSelfHeal | default $.Values.default.app.autoSelfHeal | default true }}
  {{- end }}

  source:
    repoURL: {{ $val.source.repoURL | default $.Values.default.app.source.repoURL | quote }}
    targetRevision: {{ $val.source.targetRevision | default $.Values.default.app.source.targetRevision | quote }}
    path: {{ $val.source.path | required (printf "No source.path specified for %s" $key) | quote }}

{{- if $val.source.extraSourceFields }}
{{ tpl $val.source.extraSourceFields $ | indent 4 }}
{{- else if $.Values.default.app.source.extraSourceFields }}
{{ tpl $.Values.default.app.source.extraSourceFields $ | indent 4 }}
{{- end }}

    {{- end }}
  {{- end }}
{{- end }}
