{{- $envs := required "environments is required" .Values.environments -}}

{{- range $env, $envCfg := $envs }}
  {{- range $appName, $appCfg := $.Values.applications }}

    {{- $enabled := index $appCfg.enabled $env | default false -}}
    {{- if $enabled }}

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $env }}-{{ $appName }}
  namespace: argocd
spec:
  destination:
    namespace: {{ $appCfg.destination.namespace | default $envCfg.namespace | quote }}
    server: {{ $appCfg.destination.server | default $.Values.default.app.destination.server | quote }}

  project: {{ $.Values.projectOverride | default $appCfg.project | default $.Values.default.app.project | quote }}

  {{- if $appCfg.enableAutoSync | default $.Values.default.app.enableAutoSync }}
  syncPolicy:
    automated:
      prune: {{ $appCfg.autoSyncPrune | default $.Values.default.app.autoSyncPrune | default true }}
      selfHeal: {{ $appCfg.autoSelfHeal | default $.Values.default.app.autoSelfHeal | default true }}
  {{- end }}

  source:
    repoURL: {{ $appCfg.source.repoURL | default $.Values.default.app.source.repoURL | quote }}
    targetRevision: {{ $appCfg.source.targetRevision | default $.Values.default.app.source.targetRevision | quote }}
    path: {{ required (printf "No source.path specified for %s" $appName) $appCfg.source.path | quote }}

{{- if $appCfg.source.extraSourceFields }}
{{ tpl $appCfg.source.extraSourceFields (dict "Values" $.Values "Release" $.Release "Chart" $.Chart "Capabilities" $.Capabilities "Template" $.Template "env" $env "envCfg" $envCfg "appName" $appName "appCfg" $appCfg) | indent 4 }}
{{- else if $.Values.default.app.source.extraSourceFields }}
{{ tpl $.Values.default.app.source.extraSourceFields (dict "Values" $.Values "Release" $.Release "Chart" $.Chart "Capabilities" $.Capabilities "Template" $.Template "env" $env "envCfg" $envCfg "appName" $appName "appCfg" $appCfg) | indent 4 }}
{{- end }}

    {{- end }}
  {{- end }}
{{- end }}
