apiVersion: v2
name: devops-tech-challenge-wrapper
description: Wrapper chart that pulls devops-tech-challenge from JFrog OCI
type: application
version: 0.1.0

dependencies:
  - name: devops-tech-challenge
    version: "0.1.0"
    repository: "oci://trial29e6cp.jfrog.io/docker-trial"
