devops-tech-challenge:
  app:
    image:
      repository: trial29e6cp.jfrog.io/docker-trial/devops-tech-challenge-app
      tag: "docker-4414e58b"
    env:
      NODE_ENV: "prod"
      MONGO_DB: "visitsdb_prod"
      MONGODB_URI: "mongodb://root:rootpass@mongo:27017/visitsdb_test?authSource=admin"

  mongo:
    database: "visitsdb_prod"

  ingress:
    enabled: true
    className: nginx
    host: "test.3.123.115.73.nip.io"
    path: /
    pathType: Prefix
